# Generated by Django 5.2.5 on 2025-11-06 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        help_text="Время, когда необходимо выполнять привычку"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания(в днях)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время, которое потратит пользователь на выполнение привычки в секундах(максимум 120 сек)",
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        choices=[(True, "Общий доступ"), (False, "Личное пользование")],
                        help_text="Общий доступ для привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=True,
                        help_text="Индикатор приятной привычки (only True)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="Reword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Название вознаграждения")),
                ("description", models.CharField(help_text="Описание вознаграждения")),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.CreateModel(
            name="UsefulHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        help_text="Время, когда необходимо выполнять привычку"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания(в днях)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время, которое потратит пользователь на выполнение привычки в секундах(максимум 120 сек)",
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        choices=[(True, "Общий доступ"), (False, "Личное пользование")],
                        help_text="Общий доступ для привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Индикатор полезной привычки (only False)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
    ]
