# Generated by Django 5.2.5 on 2025-11-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pleasanthabit",
            name="owner",
            field=models.ForeignKey(
                help_text="Создатель привычки",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="owner",
            field=models.ForeignKey(
                help_text="Создатель привычки",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная привычка (взаимоисключающая с Вознаграждением)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.pleasanthabit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="reword",
            field=models.ForeignKey(
                blank=True,
                help_text="Вознаграждение за выполнение привычки(взаимоисключающая со Связанной привычкой)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.reword",
                verbose_name="Вознаграждение",
            ),
        ),
    ]
