# Generated by Django 5.2.5 on 2025-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_usefulhabit_last_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefulhabit",
            name="last_execution",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Дата и время последнего выполнения привычки (None - не выполнялась)",
                null=True,
            ),
        ),
    ]
